### PR TITLE
Added Install from PyPI

### PR DESCRIPTION
**Pull request by terrytangyuan**

### CODE REVIEW

**Comment by perimosocordiae** [comment]
Looks good.

**Comment by terrytangyuan** [comment]
Actually, can you add a new line before the line for pip install? Didn't check after commit...

**Comment by perimosocordiae** [comment]
Oops, that's what I get for merging from my phone! Fixed by 648684bea668d9c3c694d652103aa22190d1f7ec.

**Comment by terrytangyuan** [comment]
Thanks!

**Pull request merged**
